version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: reachinbox-elasticsearch
    environment:
      - node.name=es01
      - cluster.name=reachinbox-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - reachinbox-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: reachinbox-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - reachinbox-network

volumes:
  elasticsearch_data:
    driver: local

networks:
  reachinbox-network:
    driver: bridge
